apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: nikhilkhanna03/tickets:latest
          env:
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: ES_URL
              value: http://elasticsearch-loadbalancer:9200
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb://tickets-mongo-srv:27017/tickets
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: ES_CLOUD_ID
              valueFrom:
                secretKeyRef:
                  name: es-cloud-id
                  key: ES_CLOUD_ID
            - name: ES_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: es-auth-user
                  key: ES_AUTH_USER
            - name: ES_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-auth-password
                  key: ES_AUTH_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 4000
      targetPort: 4000
